apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: init-config
    image: busybox
    command: ['sh','-c','echo "configured" > /mnt/config/data.txt']
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/config
  containers:
  - name: main
    image: busybox
    command: ['sh','-c','echo "Main container sees: $(cat /mnt/config/data.txt)"; sleep 3600']
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/config
  - name: sidecar
    image: busybox
    command: ['sh','-c','tail -f /mnt/config/data.txt']
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/config
