apiVersion: v1
kind: Pod
metadata:
  name: simple-web
spec:
  containers:
  - name: nginx
    image: nginx:1.25.3
    command: ["nginx","-g","daemon off;"]
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10

