apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Parsers_File parsers.conf
        Log_Level    info
        # storage.path  /fluent-bit/state
        # storage.sync  normal

    [INPUT]
        Name               tail
        Path               /var/log/containers/*.log
        Parser             cri
        Tag                kube.*
        Mem_Buf_Limit      50MB
        Skip_Long_Lines    On
        Refresh_Interval   10
        Read_from_Head     On
        Ignore_Older       24h
        DB                 /fluent-bit/state/flb.db
        DB.Sync            Normal
        inotify_watcher    false

    [FILTER]
        Name                 kubernetes
        Match                kube.*
        Kube_Tag_Prefix      kube.var.log.containers.
        Kube_URL             https://kubernetes.default.svc:443
        Merge_Log            On
        Keep_Log             Off
        K8S-Logging.Parser   On
        K8S-Logging.Exclude  Off
        Kube_Meta_Cache_TTL  300s

    [OUTPUT]
        Name                 es
        Match                kube.*
        Host                 elasticsearch.logging.svc.cluster.local
        Port                 9200
        Suppress_Type_Name   On
        # Write daily indices with this prefix => kubernetes-logs-YYYY.MM.DD
        Logstash_Format      On
        Logstash_Prefix      kubernetes-logs
        Logstash_DateFormat  %Y.%m.%d

        # Auth to Elasticsearch
        HTTP_User            elastic
        HTTP_Passwd          ${ELASTIC_PASSWORD}

        Replace_Dots         On
        Retry_Limit          False

  parsers.conf: |
    [PARSER]
        Name   cri
        Format regex
        Regex  ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep    On
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - operator: "Exists"
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-auth
                  key: ELASTIC_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
            - name: state
              mountPath: /fluent-bit/state
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: config
          configMap:
            name: fluent-bit-config
        - name: state
          emptyDir: {}
