apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-elasticsearch
  namespace: logging
spec:
  selector:
    matchLabels:
      app: sysctl-elasticsearch
  template:
    metadata:
      labels:
        app: sysctl-elasticsearch
    spec:
      hostPID: true
      tolerations:
        - operator: "Exists"
      containers:
        - name: sysctl
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              echo "Setting vm.max_map_count and fs.file-max for Elasticsearch..."
              sysctl -w vm.max_map_count=262144
              sysctl -w fs.file-max=1048576
              sleep 86400
