apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: set-permissions
          image: busybox:1.36
          securityContext:
            privileged: true
          command: ["/bin/sh", "-lc"]
          args:
            - |
              mkdir -p /host/elasticsearch-data
              chown -R 1000:1000 /host/elasticsearch-data || true
          volumeMounts:
            - name: es-hostpath
              mountPath: /host
        - name: sysctl-bootstrap
          image: busybox:1.36
          securityContext:
            privileged: true
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -e
              sysctl -w vm.max_map_count=262144
              sysctl -w fs.file-max=1048576
              sysctl -w fs.inotify.max_user_instances=2048
              sysctl -w fs.inotify.max_user_watches=1048576
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: node.store.allow_mmap
              value: "false"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-auth
                  key: ELASTIC_PASSWORD
          volumeMounts:
            - name: es-hostpath
              mountPath: /usr/share/elasticsearch/data
              subPath: elasticsearch-data
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 750m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
      volumes:
        - name: es-hostpath
          hostPath:
            path: /var/lib/elasticsearch
            type: DirectoryOrCreate
