apiVersion: v1
kind: Pod
metadata:
  name: config-reader
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","echo APP_COLOR=$APP_COLOR, APP_MODE=$APP_MODE; sleep 3600"]
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_MODE
