apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: portfolio
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      port: 80        # Service port
      targetPort: 80  # Container port
  type: ClusterIP
