apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
  labels: { app: cloudflared }
spec:
  replicas: 2
  selector:
    matchLabels: { app: cloudflared }
  template:
    metadata:
      labels: { app: cloudflared }
    spec:
      serviceAccountName: cloudflared
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token    # <-- Secret created at deploy time
                  key: TUNNEL_TOKEN
          readinessProbe:
            httpGet: { path: /ready, port: 2000 }
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /ready, port: 2000 }
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 6
          ports:
            - name: metrics
              containerPort: 2000
              protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: cloudflared
